### ISSUE TITLE
Makefile has both : and :: entries

### ISSUE THREAD

**Issue by jpmens** [relayr/xdk-mqtt#2]
Following the instructions in the README for both Linux and Mac OS/X results in not being able to build due to

```
Makefile:104: *** target file `debug' has both : and :: entries.  Stop.
```

The steps I took:

1. Install XDK-Workbench on Windows (version `install_XDK-1.5.0-SNAPSHOT-20151109_1154-x86_64.exe`)
2. zip up the installed directory and extract on Unix
3. install prerequisites as described (Paho, JSMN, gcc-arm, etc)
4. Clone this repo
5. apply patch to `Makefile` as shown below
6. run `make` (`GNU Make 4.0` respectively `GNU Make 3.81`)

I patched the `Makefile` as follows because the included `application.mk` couldn't be found otherwise.

```patch
diff --git a/make/Makefile b/make/Makefile
index 7b489ca..bee7ab8 100755
--- a/make/Makefile
+++ b/make/Makefile
@@ -18,7 +18,7 @@ APPLICATION_DIR=..
 JSMN_DIR = $(JSMN)
 PAHO_PACKET_DIR = $(PAHO_PKT)

-include $(BCDS_BASE_DIR)/xdk110/make/application.mk
+include $(BCDS_BASE_DIR)/xdk110/Common/application.mk

 PROJECTNAME = relayrxdk
 override CFLAGS += $(CFLAGS_APP)
```

Do you have a `Makefile` which works cleanly?

**Comment by marogi** [comment]
Hi,

Thanks for report.

You see this error, because XDK SDK folder layout changed and application.mk was moved (the SDK used for this project had application.mk in make directory). I do not want to drop support for the previous SDK version yet, so we'll figure a way to support both.

Br,
M

**Comment by jpmens** [comment]
Would the layout of XDK SDK `install_XDK-1.3.0-SNAPSHOT-20150603_0947-x86_64.exe` work?

**Comment by marogi** [comment]
I do not have the installation file right now, but if the layout in v1.3 is still $(BCDS_BASE_DIR)/xdk110/make/application.mk, then yes - repo will work.

**Comment by jpmens** [comment]
It looks much better, yes. I cannot though find anything related to `-c`:  it's as though some variable remains undefined, but I don't see which

```
$ make
make: -c: Command not found
make: -c: Command not found
make: -c: Command not found
make: -c: No such file or directory
make: *** [createcredentials] Error 1
```

**Comment by jpmens** [comment]
The magic, on both Linux and Mac OS, is to run `make SHELL=sh` (!)

As a side note, this has never, ever been compiled on Linux, which has a case-sensitive file system; there are dozens of includes which are spelled differently (e.g. `PIp.h` vs. `Pip.h`).

**Comment by marogi** [comment]
Yes, SHELL variable has to be aligned to one on host (zsh/bash/csh are just to different). 

In my SDK installation there's only "PIp.h" version - do you know where does the Pip.h come from?

Also, a question - in initial post you mentioned XDK-1.5.0 - I can see that the latest version available on XDK community is v1.3. Do you have a different source of XDK SDKs?

**Comment by jpmens** [comment]
There is only one `PIp.h`, yes. What I really meant is that the SDK sometimes uses `PIp.h` and others `Pip.h` (different case) meaning it just won't build on a case-sensitive host.

Well, I don't really know if it's 1.5, but the filename contains that string ... I've used the 1.3.0 file now as that allows me to build your code.

Time for me to ask a different question then: do you know how I could flash the XDK from a Mac? It appears to require a special bit of hardware, is that correct?

**Comment by marogi** [comment]
Yes - flashing on OSX requires Segger JLink debug probe.

@File names: This we can bring up on the XDK community website, so maintainers of SDK are aware.

**Comment by Marchcyr** [comment]
Can all of this info be posted to the existing instruction set for bring up
of an xdk?

**Comment by marogi** [comment]
XDK SDK v1.3 and Segger debug probe (for OSX/Linux) dependencies are now explicitly mentioned in README.md.

@jpmens : Is there anything else we can help you with?

**Comment by jpmens** [comment]
@marogi thanks, not at the moment, at least not with the current version of the code and 1.3.0 XDK SDK. I have been able to compile (on OS/X) and flash (on Windows) thanks to all your help.

**Comment by marogi** [comment]
Great! I'll close this issue now, but if you have any other problems bring it up - we are happy to solve it.

**Comment by Marchcyr** [comment]
JP Mens,

Just curious, but how did you actually get one of the XDK's as they are not
officially released?

**Comment by knaegele** [comment]
Actually they are released since CES. But right now I gave them two to test.

To the above mentioned things: you figured out correctly that there are many (semantic) changes in 1.5 (still beta - but which will be released soon). Good to have a patch already! 
Keep up the good work!
