### ISSUE TITLE
Licence ?

### ISSUE THREAD

**Issue by maxime-gaudron** [relayr/xdk-mqtt#3]
Hello,

could you add a licence file please ?

**Comment by marogi** [comment]
Hi,

Sorry for late reply - I started the process to get the correct license. Once it's done I'll update the repo.

**Comment by maxime-gaudron** [comment]
Great !
I hope it'll be a MIT licence like your other repositories :
https://github.com/relayr/node-relayr/blob/master/LICENSE
https://github.com/relayr/android-sdk/blob/master/LICENSE
https://github.com/relayr/java-sdk-example/blob/master/LICENSE

**Comment by marogi** [comment]
And done with b63b3865a7f9e63e8ca87d25da6fdfe5eb1541e9. 
It is MIT.
