### ISSUE TITLE
OS_operatingSystem_ih.h deprecated in XDK Workbench 1.5.2 

### ISSUE THREAD

**Issue by waldimiro** [relayr/xdk-mqtt#7]
OS_operatingSystem_ih.h is referenced on inc/task.h, src/main.c, ...

Please refer to
http://xdk.bosch-connectivity.com/liferay-mb/-/message_boards/message/119172

XDK Workbench version 1.5 is no more dowloadable.

**Comment by edsonaoki** [comment]
Hi. I have exactly the same problem. I cannot compile the code because of the references to OS_operatingSystem_ih.h, which does not exist in the versions of the XDK Workbench available for download.

**Comment by tomaskrcka** [comment]
The version 1.6.0 is supported now - see pull request #9
